version: '3'
services:
  app:
    build: .
    image: pass-exam
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
      - static_volume:/var/www

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  static_volume:
  db_volume:
